# Generated by Django 3.1.2 on 2021-01-15 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_description', models.CharField(max_length=250)),
                ('address_lat', models.CharField(max_length=30)),
                ('address_lon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateTimeField()),
                ('user_role', models.CharField(db_index=True, max_length=10, null=True)),
                ('imageurl', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('phone', models.CharField(max_length=24)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=30, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='webApp.customer')),
            ],
        ),
    ]
